"""
Django settings for nrm_app project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ
from corsheaders.defaults import default_headers

env = environ.Env()
ENV_FILE = Path(__file__).resolve().parent / ".env"
environ.Env.read_env(str(ENV_FILE))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
os.environ.setdefault("BACKEND_DIR", str(BASE_DIR))


def resolve_env_path(name, default="", *, trailing_sep=False):
    raw_value = str(os.environ.get(name, default) or "").strip()
    if not raw_value:
        return ""

    raw_value = os.path.expandvars(raw_value)
    candidate = Path(raw_value).expanduser()
    if not candidate.is_absolute():
        candidate = BASE_DIR / candidate

    resolved = os.path.normpath(str(candidate))
    if trailing_sep:
        resolved = resolved.rstrip("/\\") + os.sep
    return resolved


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# TMP File location
TMP_LOCATION = resolve_env_path(
    "TMP_LOCATION", default="$BACKEND_DIR/tmp", trailing_sep=True
)

# MARK: ODK Login Creds
ODK_USERNAME = env("ODK_USERNAME")
AUTH_TOKEN_FB_META = env("AUTH_TOKEN_FB_META")
ODK_PASSWORD = env("ODK_PASSWORD")
DEPLOYMENT_DIR = resolve_env_path("DEPLOYMENT_DIR", default="$BACKEND_DIR")
# MARK: ODK Sync Creds
ODK_USER_EMAIL_SYNC = env("ODK_USER_EMAIL_SYNC")
ODK_USER_PASSWORD_SYNC = env("ODK_USER_PASSWORD_SYNC")

# MARK: DB settings
DB_NAME = env("DB_NAME")
DB_USER = env("DB_USER")
DB_PASSWORD = env("DB_PASSWORD")

USERNAME_GESDISC = env("USERNAME_GESDISC")
PASSWORD_GESDISC = env("PASSWORD_GESDISC")

STATIC_ROOT = "static/"
GEE_HELPER_ACCOUNT_ID = env("GEE_HELPER_ACCOUNT_ID")
GEE_DEFAULT_ACCOUNT_ID = env("GEE_DEFAULT_ACCOUNT_ID")
ADMIN_GROUP_ID = env("ADMIN_GROUP_ID")
ALLOWED_HOSTS = [
    "geoserver.core-stack.org",
    "127.0.0.1",
    "localhost",
    "0.0.0.0",
    "api-doc.core-stack.org",
    "2f2de623c34b.ngrok-free.app",
    "odk.core-stack.org",
    "unrecognizably-deft-aimee.ngrok-free.dev",
]
CE_API_URL = env("CE_API_URL")
CE_BUCKET_NAME = env("CE_BUCKET_NAME")
# MARK: Django Apps

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    # core apps
    "computing",
    "dpr",
    "geoadmin",
    "stats_generator",
    # rest framework for APIs
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_yasg",
    "rest_framework_api_key",
    # project applications
    "organization.apps.OrganizationConfig",
    "projects",
    "plantations",
    "plans",
    "public_api",
    "community_engagement",
    "bot_interface",
    "gee_computing",
    "waterrejuvenation",
    "apiadmin",
    "moderation",
    "users.apps.UsersConfig",
    "status_monitor",
]

# MARK: CORS Settings

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        "http://gramvaanimoderationtest.s3-website.ap-south-1.amazonaws.com",
        "https://nrm.core-stack.org",
        "https://nrm.gramvaanidev.org",
        "https://dashboard.core-stack.org",
        "https://feature-logout-functionality.d2u6quqcimqsuk.amplifyapp.com",
        "https://uat.dashboard.core-stack.org",
        "https://www.explorer.core-stack.org",
        "https://development.d2s4eeyazvtd2g.amplifyapp.com",
        "http://127.0.0.1:8000",
        "http://127.0.0.1:3000",
        "http://127.0.0.1",
        "http://localhost:3000",
        "http://localhost:3001",
    ]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
    r"^http://192\.168\.\d{1,3}\.\d{1,3}(:\d+)?$",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
    "content-disposition",  # Important for file uploads in form data
    "X-API-Key",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = ["http://localhost:3000"]

# MARK: REST Framework

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": [
        "utilities.renderers.RoundedJSONRenderer",
    ],
}

# MARK: JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=90),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=120),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    # "apiadmin.middleware.ApiHitLoggerMiddleware",
]

ROOT_URLCONF = "nrm_app.urls"

# MARK: Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "nrm_app.wsgi.application"

DATA_UPLOAD_MAX_NUMBER_FILES = 1000

# MARK: Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": "127.0.0.1",
        "PORT": "",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True

# Celery
CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
AUTH_USER_MODEL = "users.User"

STATIC_URL = "static/"
STATIC_ROOT = "static/"
ASSET_DIR = "/home/ubuntu/cfpt/core-stack-backend/assets/"

# Media files (User uploaded content)
MEDIA_ROOT = os.path.join(BASE_DIR, "data/")
MEDIA_URL = "/media/"

EXCEL_PATH = resolve_env_path("EXCEL_PATH", default="$BACKEND_DIR", trailing_sep=True)
EXCEL_DIR = resolve_env_path(
    "EXCEL_DIR",
    default="$BACKEND_DIR/data/excel_files",
    trailing_sep=True,
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # keep Django's default loggers
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} | {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "mail_admins": {
            "class": "django.utils.log.AdminEmailHandler",
            "level": "ERROR",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "geoadmin": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# MARK: Report requirements
OVERPASS_URL = env("OVERPASS_URL")

# MARK: Email Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtpout.secureserver.net"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_TIMEOUT = 30
PASSWORD_RESET_TIMEOUT = 259200  # 3 days in seconds

GEOSERVER_URL = env("GEOSERVER_URL", default="")
GEOSERVER_USERNAME = env("GEOSERVER_USERNAME", default="")
GEOSERVER_PASSWORD = env("GEOSERVER_PASSWORD", default="")

PROD_GEOSERVER_URL = env("PROD_GEOSERVER_URL", default="")
PROD_GEOSERVER_USERNAME = env("PROD_GEOSERVER_USERNAME", default="")
PROD_GEOSERVER_PASSWORD = env("PROD_GEOSERVER_PASSWORD", default="")

PROD_BACKEND_URL = env("PROD_BACKEND_URL", default="")
PROD_BACKEND_API_KEY = env("PROD_BACKEND_API_KEY", default="")


CE_BUCKET_URL = env("CE_BUCKET_URL")
EARTH_DATA_USER = env("EARTH_DATA_USER")
EARTH_DATA_PASSWORD = env("EARTH_DATA_PASSWORD")

GEE_SERVICE_ACCOUNT_KEY_PATH = env("GEE_SERVICE_ACCOUNT_KEY_PATH")
GEE_HELPER_SERVICE_ACCOUNT_KEY_PATH = env("GEE_HELPER_SERVICE_ACCOUNT_KEY_PATH")
GEE_DATASETS_SERVICE_ACCOUNT_KEY_PATH = env("GEE_DATASETS_SERVICE_ACCOUNT_KEY_PATH")

# gcs bucket
GCS_BUCKET_NAME = env("GCS_BUCKET_NAME")

LOCAL_COMPUTE_API_URL = env("LOCAL_COMPUTE_API_URL")

# MongoDB cache settings (optional)
MONGODB_URI = env("MONGODB_URI", default="")
MONGODB_DB_NAME = env("MONGODB_DB_NAME", default="core_stack")
MONGODB_WATERBODIES_COLLECTION = env(
    "MONGODB_WATERBODIES_COLLECTION", default="waterbodies_cache"
)
MONGODB_PUBLIC_API_V2_COLLECTION = env(
    "MONGODB_PUBLIC_API_V2_COLLECTION", default="public_api_mws_v2_cache"
)

# NREGA settings
NREGA_BUCKET = env("NREGA_BUCKET")

# S3 access keys
S3_SECRET_KEY = env("S3_SECRET_KEY")
S3_ACCESS_KEY = env("S3_ACCESS_KEY")

# S3 settings
S3_BUCKET = env("S3_BUCKET")
S3_REGION = env("S3_REGION")

# DPR S3 settings
DPR_S3_SECRET_KEY = env("DPR_S3_SECRET_KEY", default="")
DPR_S3_ACCESS_KEY = env("DPR_S3_ACCESS_KEY", default="")
DPR_S3_REGION = env("DPR_S3_REGION", default="")
DPR_S3_BUCKET = env("DPR_S3_BUCKET", default="")
DPR_S3_FOLDER = env("DPR_S3_FOLDER", default="")

# bot_interface settings
AUTH_TOKEN_360 = env("AUTH_TOKEN_360")
ES_AUTH = env("ES_AUTH")
CALL_PATCH_API_KEY = env("CALL_PATCH_API_KEY")

# Community Engagement API Configuration
WHATSAPP_MEDIA_PATH = resolve_env_path(
    "WHATSAPP_MEDIA_PATH",
    default="$BACKEND_DIR/bot_interface/whatsapp_media",
    trailing_sep=True,
)

BASE_URL = "https://geoserver.core-stack.org/"
DEFAULT_FROM_EMAIL = "CoreStackSupport <contact@core-stack.org>"

PLAN_REPORT_RECIPIENTS = env.list("PLAN_REPORT_RECIPIENTS", default=[])

FERNET_KEY = env("FERNET_KEY")

API_KEY = env("API_KEY", default="")


lulc_years = [
    "2017_2018",
    "2018_2019",
    "2019_2020",
    "2020_2021",
    "2021_2022",
    "2022_2023",
    "2023_2024",
]
water_classes = [2, 3, 4]

GEE_STORAGE_PROJECT = env("GEE_STORAGE_PROJECT")
